### ISSUE TITLE
Analyse the dir upload 

### ISSUE THREAD

**Issue by zepouet** [Treeptik/cloudunit#101]
Instead of file upload, try to analyse the cost for a directory upload

**Comment by GuillaumeUnice** [comment]
@zepouet  Done in [https://github.com/Treeptik/cloudunit/tree/101-directoryExplorer](url)

**Comment by GuillaumeUnice** [comment]
@zepouet I would like a route that return content file in text format with the following format :

```
/unzip/file/container/:containerId/application/:applicationName/path/:path
```
in POST

and add for zip file a "zipable" property.
