### ISSUE TITLE
Create a new field into Explorer to create directory

### ISSUE THREAD

**Issue by zepouet** [Treeptik/cloudunit#102]
We may need to create directory before upload file. Add this new field into webui. 
The submit will be on a new route (fake into file controller) to always answer ok.

**Comment by GuillaumeUnice** [comment]
@zepouet Could you add logic in backend to create directory in FileController.java line 231 in [https://github.com/Treeptik/cloudunit/tree/101-directoryExplorer](url)

**Comment by zepouet** [comment]
Is it possinle to have input field at first before the list ?

Thanks.

**Comment by zepouet** [comment]
Can you test with Firefox and Chrome ? I think there is problem refresh if we click too quickly

**Comment by GuillaumeUnice** [comment]
Done
