### ISSUE TITLE
UI enhancements

### ISSUE THREAD

**Issue by zepouet** [Treeptik/cloudunit#105]
1- Add a spinner logo to inform user that an action is performing when we deploy an application. 
To reproduce create an tomcat8 + mysql + use this war : https://github.com/Treeptik/cloudunit/releases/download/1.0/pizzashop-mysql.war

2 - Add mini thumbnail into dashboard panel for server and module

3 - A new filter into dashboard panel for filtering server

4 - Add two new fake module (influxdb is available) in disabled grey mode

Thanks

**Comment by GuillaumeUnice** [comment]
5 - problem alignement in explorer tab create button's directory when directory removable below

**Comment by GuillaumeUnice** [comment]
@zepouet About filter into dashboard panel I would like a route wich return groupServer (Tomcat, Jboss, etc) with the following structure : 

```
{
  id: prefixId,
  title: prefixEnv
}
```

Thanks

**Comment by GuillaumeUnice** [comment]
1. Done
2. Initialize miss svg image
3. Waiting backend route
4. Done
5. Done
