### ISSUE TITLE
Cannot delete an app in error

### ISSUE THREAD

**Issue by zepouet** [Treeptik/cloudunit#106]
If an application is in error, we should be able to delete it. At the moment, the button is grey so we need to go into database.

**Comment by zepouet** [comment]
@GuillaumeMartial Can you verify that we clean everything properly (containers, database...).
To create an error, try to create lot of applications. Without memory you will have errors

**Comment by GuillaumeMartial** [comment]
@zepouet this error "Driver aufs failed to remove root filesystem..." occures. I need to rebuild all my dev env. However, now, to delete app, pending status is not blocking anymore
