### ISSUE TITLE
Add WYSIWYG in explorer tab

### ISSUE THREAD

**Issue by GuillaumeUnice** [Treeptik/cloudunit#108]
To be able to edit a file in explorer with in a pop up.

**Comment by GuillaumeUnice** [comment]
@zepouet I would like a route that return content file in text format with the following format : 

```
/content/file/container/:containerId/application/:applicationName/path/:path
```
in GET and PUT

and add in editable file a property "editable".

**Comment by zepouet** [comment]
I would like a route that return content file in text format with the following format :

/unzip/file/container/:containerId/application/:applicationName/path/:path // POST

**Comment by GuillaumeUnice** [comment]
@zepouet Done

**Comment by GuillaumeUnice** [comment]
Syntax color done
