### ISSUE TITLE
Cannot cancel an upload 

### ISSUE THREAD

**Issue by zepouet** [Treeptik/cloudunit#109]
To reproduce you need to have a big file to upload in local mode because it is so quick.
In production it is easier to reproduce between network latency
Cancel button is not right. No action

**Comment by Kan23** [comment]
We cannot cancel a deployment upload because, when we deployed a package, this is not the front which handle the deployment. One solution is to stop and remove deployement after upload in backend.

**Comment by GuillaumeUnice** [comment]
@zepouet Done.
