### ISSUE TITLE
Test the new file Explorer at limit

### ISSUE THREAD

**Issue by zepouet** [Treeptik/cloudunit#111]
Test all possibility to find bug (backend or fronted).
Please add all issues here as comment. We will open ticket if needed.

**Comment by Kan23** [comment]
- GIF file : corrupt file when download
- File with name with space : java.lang.RuntimeException: No way to execute the command :command=mv /cloudunit//upload-2401666174593191747.pptx (Test download with docx: OK, pptx: OK, pdf: corrupt)
- Tar.gz : java.lang.RuntimeException: No way to execute the command :command=mv /cloudunit//upload-208867734537571691.gz (File inside ok)
- 7z : Ok but can't dezip
- Large file : Not over 300 Mo
- Tar.gz contained by Tar.gz : Ok but contained Tar.gz corrupt and we can't delete files on corrupt Tar.gz
- Create, Delete directory : Ok
- Upload, Edit, Delete file on created directory : OK

**Comment by zepouet** [comment]
@Kan23 Thanks for testing.
