### ISSUE TITLE
Remove module does not remove CU_ENV variable

### ISSUE THREAD

**Issue by zepouet** [Treeptik/cloudunit#115]
It is easier to see it since we have CU_ENV displayed on overview panel.

True on tomcat. Must be tested elsewhere

**Comment by GuillaumeUnice** [comment]
Then, we have to refresh in front app.

**Comment by GuillaumeUnice** [comment]
@zepouet In relation with this bug when an app is in "STOP" mode the API don't be able to return information.

**Comment by GuillaumeMartial** [comment]
FIXED
