### ISSUE TITLE
Add a verification feature after building CU images

### ISSUE THREAD

**Issue by zepouet** [Treeptik/cloudunit#126]
Need to verify the right build for images during installation or reinstallation.
For example, WildFLY10 could not be ready and no error before to try to instanciate it.

Two ways to solve it : at startup in java (for the cloudunit v2) or to enumerate the images with shell scripts

```
cloudunit/base-jessie        
cloudunit/wildfly-9          
cloudunit/wildfly-8 
cloudunit/wildfly-10         
cloudunit/redis-3-0         
cloudunit/redis-2-8         
cloudunit/mongo-2-6      
cloudunit/mysql-5-7        
cloudunit/mysql-5-6        
cloudunit/mysql-5-5        
cloudunit/postgis-2-2       
cloudunit/postgresql-9-5 
cloudunit/postgresql-9-4 
cloudunit/postgresql-9-3 
cloudunit/apache-2-2       
cloudunit/fatjar             
cloudunit/tomcat-8      
cloudunit/tomcat-7      
cloudunit/tomcat-6      
cloudunit/tomcat-appconf8
cloudunit/tomcat-appconf7
cloudunit/tomcat-appconf6
cloudunit/tomcat-base        
cloudunit/java               
cloudunit/base-16.04   
cloudunit/base-14.04   
cloudunit/base-12.04   
```

**Comment by cvandome** [comment]
This script has been added in order to test the overall docker images build success:
cu-services/check_build_images.sh 

If there is an error the script stops the global install script and list the images build errors.
