### ISSUE TITLE
Add logrotate for production env

### ISSUE THREAD

**Issue by zepouet** [Treeptik/cloudunit#136]
You can use this tutorial :
https://www.nicolashug.com/developpement/docker/docker-logrotate-gerer-facilement-logs-de-containers

Add the logrotate.conf into install script shell

**Comment by cvandome** [comment]
in  the file cloudunit/cu-production/boot.sh
**cp $CU_INSTALL_DIR/files/docker-logrotate /etc/logrotate.d/**

in the file cloudunit/cu-production/files/docker-logrotate
**/var/lib/docker/containers/*/*.log {
  rotate 7
  daily
  compress
  size=1M
  missingok
  copytruncate
}**
