### ISSUE TITLE
Add a link to download cli from WebUI panel

### ISSUE THREAD

**Issue by zepouet** [Treeptik/cloudunit#141]
Easy to do and nice for users

**Comment by zepouet** [comment]
The link is https://github.com/Treeptik/cloudunit/releases/download/1.0/CloudUnitCLI.jar

**Comment by zepouet** [comment]
@GuillaumeUnice Find a good place to display it :)

**Comment by GuillaumeUnice** [comment]
@zepouet  Done in dev
