### ISSUE TITLE
migration-112

### ISSUE THREAD

**Issue by zepouet** [Treeptik/cloudunit#142]

**Comment by zepouet** [comment]
Todo list

- [Update script to provision 1.12 ] 
- [Extract CU-API to test with Docker 1.12]

**Comment by GuillaumeUnice** [comment]
Cut the settings menu in  submenu :
* jvm configuration
* dns alias
* port to expose
* variables environnement

@Kan23 create the backend for variable environnement. To do that create a new Controller and service

**Comment by Kan23** [comment]
Environment variable : done

**Comment by GuillaumeUnice** [comment]
UI display app in dashboard by grid and list

**Comment by zepouet** [comment]
@GuillaumeUnice Are you sure to have removed all previous call for FileExplorer ?
It seems to have path with __ in the code ?

Try to delete all deprecated method in FileController to be sure. Thanks

<img width="1323" alt="capture d ecran 2016-08-12 a 20 02 16" src="https://cloud.githubusercontent.com/assets/231269/17632298/d79b90d2-60c7-11e6-8cbc-cdf8e85c9109.png">
