### ISSUE TITLE
Not valide exclusion for logs directory // GIT

### ISSUE THREAD

**Issue by zepouet** [Treeptik/cloudunit#143]
Maybe I am wrong but it seems to have a directory out of GIT 

```
webapp/scripts/editApplication/logs
```

Hard to find where it is excluded into .gitignore... ???

++

**Comment by zepouet** [comment]
It could be dangerous because any commit is never occured...

**Comment by GuillaumeUnice** [comment]
@zepouet  Indeed, done [https://github.com/Treeptik/cloudunit/commit/4301bca36c061d40421a6571be04b0973e12437b](url)
