### ISSUE TITLE
Remove all deprecated method into FileController and test the UI

### ISSUE THREAD

**Issue by zepouet** [Treeptik/cloudunit#144]
@GuillaumeUnice Are you sure to have removed all previous call for FileExplorer ?
It seems to have path with __ in the code ? 

Try to delete all deprecated method in FileController to be sure. Thanks++

<img width="1323" alt="capture d ecran 2016-08-12 a 20 02 16" src="https://cloud.githubusercontent.com/assets/231269/17632709/1d72f6ac-60ca-11e6-9a92-86c5cb2f6206.png">

**Comment by GuillaumeUnice** [comment]
@zepouet Done
