### ISSUE TITLE
Here is a problem when I excute "vagrant provision"command

### ISSUE THREAD

**Issue by 412428728** [Treeptik/cloudunit#146]
```
The SSH connection was unexpectedly closed by the remote end. This
usually indicates that SSH within the guest machine was unable to
properly start up. Please boot the VM in GUI mode to check whether
it is booting properly.
```

Above is what I've met when i do the Step 5:

```
cd $HOME/cloudunit/cu-vagrant 
vagrant up
vagrant provision
```

and the command "vagrant ssh" works.
Can you tell me what is going wrong? THANKS!

**Comment by 412428728** [comment]
Here is my pc :
Linux xh-OptiPlex-990 4.2.0-35-generic #40~14.04.1-Ubuntu SMP Fri Mar 18 16:37:35 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by GuillaumeMartial** [comment]
Hi,
I think you needn't do a new provision after `vagrant up`, if all is ok. Have you got any errors during `vagrant up`?

Go to Step 6 directly, it should work. If you have others problems, let us know.
