### ISSUE TITLE
CloudUnit cluster install

### ISSUE THREAD

**Issue by pdaniel-frk** [Treeptik/cloudunit#159]
Hello,

I cannot see the documentation for cloudunit cluster install. Does cloudunit runs in a cluster mode?

Regards

**Comment by zepouet** [comment]
Hello @pdaniel-frk, sorry for the delay. At the moment we cannot use cluster mode.
It will be a feature in a next sprint. Before we will introduce Nexus and Docker Registry to store images. Just after that, we will start to code this feature. During previous months, we changed lot of codes to be docker 1.12 compliant and now it is great.

For which usage, do you need cluster ? Overlay network between database and application servers ?

Thanks
