### ISSUE TITLE
Grouping modules by type

### ISSUE THREAD

**Issue by GuillaumeMartial** [Treeptik/cloudunit#164]
Nice to have : 
- Grouping module by type : DATABASE, DATAGRID, MESSAGE_BROKER...
- some refresh problem on module creation, all env variables are not displayed without a refresh action

**Comment by zepouet** [comment]
Refresh action should not be corrected. Need to be checked it.
I don't understand where you want to display modules groups ?

**Comment by GuillaumeMartial** [comment]
On the module selection page. Having a card by group could be useful to sort them when there will be a lot of modules. It's not a priority for the moment.
Refresh env vars and ports is not fixed yet
