### ISSUE TITLE
Option Group broken into UI

### ISSUE THREAD

**Issue by zepouet** [Treeptik/cloudunit#201]
No way to have groups about servers (tomcat, wildfly...)
The Angular UI is broken.

@GuillaumeUnice I don't understand if the problem is into the backend or frontweb. 
If you can have time to watch, it is nice. For the moment I removed the group

Only Wildlfy was right ? All other servers had no group.

**Comment by zepouet** [comment]
The field is set to **undef** into 
`cu-manager-ui/app/scripts/components/dashboard/dashboard.createApplication.js`

**Comment by GuillaumeUnice** [comment]
Done: https://github.com/Treeptik/cloudunit/commit/78a68fde9f092930aa6ec1b1dfa5b5ff68be0c70
