### ISSUE TITLE
New admin dashboard for pulling images

### ISSUE THREAD

**Issue by zepouet** [Treeptik/cloudunit#204]
Create a new page restricted to admin user.

We need to display all images (servers and modules) and have the blocking option to pull the missing images. In the future we could deliver CloudUnit without all images and user could choose to activate them

**Comment by GuillaumeUnice** [comment]
There is two options for each images:
-Pull / Remove
-Enable / Disable (enable if image already pulled)

You just have to add a boolean column in image table for activate property

**Comment by GuillaumeUnice** [comment]
Done
