### ISSUE TITLE
Trafik and dns problems

### ISSUE THREAD

**Issue by ZYecho** [Treeptik/cloudunit#207]
hello, I want to know if I deploy a cloudunit server in machine A, and When I get http://gitlab.cloudunit.dev in machine B, how can I find the gitlab service without the dns from gitlab.cloudunit.dev to machine A.
I did't see any dns configuration in scripts according to documentation/SERVER-GUIDE.md.

thx～

**Comment by punkstarman** [comment]
Hi ZYecho,

In general, DNS configuration is up to you. The server guide assumes that you have a registered domain name and DNS entries the point the domain name and all its sub-domains to the IP address of the machine on which CloudUnit will be installed. This is not entirely clear from the server guide, so we will add an item to the requirements section.

The *.cloudunit.dev domain names are suggested for use in a local development environment. [The corresponding guide](https://github.com/Treeptik/cloudunit/blob/dev/documentation/DEV-GUIDE-LINUX.md) suggests using dnsmasq as a local DNS to map *.cloudunit.dev to the IP of the virtual machine that houses the development environment.

**Comment by zepouet** [comment]
Hi ZYecho,

You could use .xip.io to skip dnsmasq. Do not forget that .dev is for developpement.
For production, it could better to use your own address or external service as .xip.io
For example : ping 192.168.50.4.xip.io will redirect to  192.168.50.4
Tell us if not clear. Thanks @punkstarman too

Nicolas

**Comment by ZYecho** [comment]
Thanks  @zepouet @punkstarman  xip.io is great. I think it's good to add xip.io to document for people who don't want to use dns server.
