### ISSUE TITLE
application deploy file type

### ISSUE THREAD

**Issue by ZYecho** [Treeptik/cloudunit#211]
hello,
Does cloudunit support delpoy jar/ear/war? or each server support different types? Any documentation about that? I just saw filter jar/ear/war three types in createApplication.js, but when I use tomcat as server, the deploy.sh in tomcat docker image only support war, is there more work to do?

**Comment by zepouet** [comment]
Hello,

We support only war with tomcat because no way to deploy ear or jar with it.
For Jboss we support EAR. What type of applications do you want to deploy ?

Thanks

**Comment by ZYecho** [comment]
Thanks for reply.
I think we should filter file type according to server type. for example, if I select a tomcat, only war should be allowed. but in createApplication.js, it just filter jar/ear/war.

**Comment by ZYecho** [comment]
If I want to deploy jar, how can I do?

**Comment by ZYecho** [comment]
Hi, I also want to know how to use apache、nginx、fatjar in cloudunit, any documentation about that? I don't find deploy.sh in these servers' docker image, so I don't how how to deploy app?

**Comment by zepouet** [comment]
Hello,

You can use fatjar to deploy any jar for spring-boot, vertx, batch. 
For Apache, Nginx it is more complicated because there is no simple artifact but thousand solutions. 
You must use file explorer and you have an option to unzip files. Apache is lot used with Angular App. If you want, we can have a private call to help you.

Thanks.

**Comment by ZYecho** [comment]
thanks for reply.
you mean  If I select apache or nginx as server , I must use file explorer to upload application and use command run to deploy the app? yeah, I will appreciate if you could give me a example.

**Comment by punkstarman** [comment]
No, he means that you must choose fat jar server type and use deploy menu to deploy any runnable jar. After deployment, the jar will be run automatically using a simple `java -jar <your jar>` command.

The fat jar server type is special in that the actual server must be embedded in the jar and the main class referenced in the jar's MANIFEST.MF must launch the embedded server.

Tools that can create runnable jars with embedded servers include:
- the Tomcat Maven Plugin has a goal for repackaging any war project;
- Spring Boot has Plugins for Maven and Grade that do the same thing, only that it must be a Spring application;
- the Vert.x framework in combination with the Maven Shade Plugin, makes it very easy to package a vertices as a runnable jar.

Please refer to the documentation of these projects for examples.
