### ISSUE TITLE
broken link in http://cloudunit.io/ website

### ISSUE THREAD

**Issue by tatemilio** [Treeptik/cloudunit#212]
You are a broken link in cloudunit.io, see section 
> Want to contribute to the project? You are more than welcome to do so. Learn how to set-up the dev environment...
 
the wrong link is [DEV-GUIDE.md](https://github.com/Treeptik/cloudunit/blob/master/documentation/DEV-GUIDE.md).

**Comment by zepouet** [comment]
Thanks David we will correct it.

Hope to see you again end of june.

Nicolas
