### ISSUE TITLE
Problem during the installation.

### ISSUE THREAD

**Issue by michaelcoll** [Treeptik/cloudunit#29]
Hi,

I've tried to install Cloud unit on a small VirtualBox Debian 8 server, and I'm facing a big problem.

Ansible tells me :

```
TASK: [docker-host | Copie des clés pour le serveur de dev] ****************** 
fatal: [CUserver] => error while evaluating conditional: cu_environment == "dev"

FATAL: all hosts have already failed -- aborting
```

Any clue ?

**Comment by GuillaumeMartial** [comment]
Hi Michael,
I'm looking for your problem now. Can you give us more details on your install process? Did you use a simple virtualbox or wrap it with Vagrant? Have you pulled the latest versions of the two projects CloudUnit and CUInfrastructure on the default branch (dev)?
Thank you for your interest

Guillaume

**Comment by michaelcoll** [comment]
Yes sure !

So I've created a VM on VirtualBox, installed a fresh Debian 8.2 jessy on it, and followed your guide.

I'm launching the install process from the host that runs on an Ubuntu distro.

I've not checked if I've checkout the dev branch of CUInfrastructure, I think that by default it's the master branch.

For the CloudUnit repo. it's ansible that choose what branch to checkout and I've made no change on the scripts.

I've tried to set cu_environment to dev, but this time ansible tried to copy cert files that does not exists on the server.

Thanks.

**Comment by GuillaumeMartial** [comment]
Thanks Michael. I see what you want to do. For the moment, dev and demo installation need Vagrant to work. It's the Vagrantfile that set the cu_environment into the VM. 
I'll fix the installation for your use case and I'll upgrade the documentation. I'll let you know.

Guillaume

**Comment by GuillaumeMartial** [comment]
Hi Michael,
We've investigated and we've made a full dev installation for a server (VM or bare metal) under Debian jessie, outside Vagrant. Ansible provides all elements, included default docker certificates. We are currently documenting it and we'll release it next Monday.
I'll let you know.

Thank you for your interest

Guillaume

**Comment by michaelcoll** [comment]
Thank you very much :)

**Comment by GuillaumeMartial** [comment]
Hi Michael,
You can try to install a cloudunit instance on your Debian jessy VM using this guide : https://github.com/Treeptik/CloudUnit/blob/dev/documentation/SERVER-GUIDE.md

For the moment, the default TLS certificates for Docker have been generated on Debian 7.8  so, if you install it on Ubuntu server, please refer to the official TLS Docker guide to generate your own certificates : https://docs.docker.com/engine/articles/https/ and replace all files in /home/admincu/cloudunit/certs/server by yours.

Let us know if you still have problems to do it

Guillaume

**Comment by michaelcoll** [comment]
Thanks for your help :) I'll test that ASAP.

**Comment by michaelcoll** [comment]
Hi,

I've continued my test. The first 2 scripts (installCU1.yml and installCU2.yml) works well, the third crash after the logstash installation.

As a reminder, I'm testing you solution on a VirtualBox VM with Debian 8.2 (jessy) on it. To match my future Dedicated serveur (It's a single core with 2Go of RAM with 10Go SSD. I know, it's way so under your requirements, but I wanted to test that and check if this suits my needs.

After the third script, I started the compilation part of the manual. It was little hard giving the 10Go of hard drive, but I've finally build the ROOT.war

BTW I had to launch the 2 docker-compose line in the console myself with sudo because docker refuse to connect to the daemon using the admincu user, and the sed command in the `compile-root-war.sh` script didn't worked, I had to manually edit the DockerFile and replace with user/group ids.

After that I've launched the `reset-all.sh` script. It told me that the source command doesn't exists ... (I've run the command outside of the script and that worked well.) After that, I had to add the PROFILE=prod in my `.profile` file.

After that, the script had downloaded lots of docker images, too much for my 10Go hard drive. 

I wasn't able to test further.

As a conclusion, your solution seems really good, and I will follow it closely. But it doesn't suit my actual needs.

I will continue my test on a much bigger VM.

Do you plan to release DEB or RPM packages ?

Do you plan to make optional components to reduce the memory footprint ?

Thanks and keep up the good work :)

**Comment by GuillaumeMartial** [comment]
Hi Michael,
I will add some hardware requirements to run the platform. Indeed, you can imagine that you will need more than 2 Go of RAM and 10 Go of storage. A basic installation of CloudUnit without any client application takes at least 12 Go disc space. Perhaps your installation problem is due to that. In development, we used to run the VM with 4 Go of RAM and 20 Go disc scape.  If you see the Vagrantfile, the default memory configuration is 4096 Mo. A basic application running on tomcat is launched with 512 Mo of RAM so, you will be quickly limited. For the moment, we do not plan any DEB or RPM packages, the server provision with Ansible is the more efficient way for us, due to the microservices architecture with Docker.
Try to install the platform on a bigger VM and let us know!
Thank you for your feedbacks!

Guillaume
