### ISSUE TITLE
Tag application with CloudUnit origin

### ISSUE THREAD

**Issue by fabienamico** [Treeptik/cloudunit#43]
*The goal is to allow the use of multiple instance of CloudUnit that share the same database and the same docker registry.*

Add a the name of the instance of CloudUnit in the `configuration.properties` file. The instance name will be something like DEV, QA, PROD but we must be able to write anything.  

When an application is created the name of the tag must be assigned to the application in the database. The instance of CloudUnit must show only the application with the Tag name of the instance except for the snapshot feature. 

The snapshot feature allow to create a new application in an other instance of CloudUnit, at this time the new application will have the new tag name of the CloudUnit instance.

**Comment by zepouet** [comment]
Into $HOME/.cloudunit/configuration.properties, you have to set these informations 
* instance 
* url of database
* password of database
* url of registry

For the last point, you need to create this variable. At the moment, the url of registry is localhost.

**Comment by TMAMychaL** [comment]
Should we add the instance tag name into snapshot view in order to identify where the snapshot came from ?
If yes, should we show to the users the CU instance tag name on main page (dashboard) ?

**Comment by htomaka** [comment]
see issue#42

**Comment by zepouet** [comment]
Add a new URL to an existing non-secure endpoint to know the current tag
Needed to display (dev, qa, prod...) since the login page the current env

**Comment by TMAMychaL** [comment]
Added to the new URL : /user/get-cloudunit-instance
Return the CU instance tag value.
