### ISSUE TITLE
Alias colision

### ISSUE THREAD

**Issue by zepouet** [Treeptik/cloudunit#47]
Verify if an alias as "www.foo.com" is equals or not "www.foo.com/"

These two entries should be simular so the second not allowed

**Comment by TMAMychaL** [comment]
Check has been modified. A new regular expression tests the domain name. Before the domain could begin with a hyphen which was an error.

Regex pattern matches now the following criteria :
     - The domain name should be a-z | A-Z | 0-9 and hyphen(-)
     - Last tld must be at least two characters, and a maximum of 6 characters
     - The domain name should not start or end with hyphen (-) (e.g. -google.com or google-.com)
     - The domain name can be a subdomain (e.g. treeptik.corp.eu)

**Comment by zepouet** [comment]
Can you comment the current status about this issue, please

**Comment by TMAMychaL** [comment]
Processed.
