### ISSUE TITLE
Bad Login/password

### ISSUE THREAD

**Issue by zepouet** [Treeptik/cloudunit#57]
No error displayed when the password is wrong. No urgency

**Comment by htomaka** [comment]
Will fix that, maybe need small refactoring of authentication logic

**Comment by htomaka** [comment]
Why do I get a 400 bad request when authentication fail on the login form? Should be 401 unauthorized.

**Comment by zepouet** [comment]
We have two current issue about the same problem 
https://github.com/Treeptik/cloudunit/pull/60
Can you close one of them ? And comment the right one to continue.

Thanks

**Comment by zepouet** [comment]
Great, it corrects the problem and another one meet these days.
Previously when we use a browser and create an app for example, with another browser we could not log into the application. It seems your patch correct the problem.

I will update double env (QA) and (PROD) to valid but it seems right. ++
