### ISSUE TITLE
Pushing sources / deployment with Git

### ISSUE THREAD

**Issue by TMAMychaL** [Treeptik/cloudunit#61]
Pushing the sources is functional, the application is built with Maven (Successfully) but the application is not deployed on the server (no deployment in the manager, no history in timeline)

Conditions for the test:
- Server: Tomcat 8
- Module installed: MySQL

**Comment by zepouet** [comment]
Not reproducted in dev. Testing in production env with double server and a common database/registry

**Comment by zepouet** [comment]
Error into config file for production env. Corrected
