### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by IsNull** [Treeptik/cloudunit#71]
I'm just looking into this cool project for evaluation and stumbled upon broken links in your [readme](https://github.com/Treeptik/cloudunit/blob/dev/README.md):

CloudUnit CLI guide (https://github.com/Treeptik/cloudunit/blob/dev/documentation/README.md)
CloudUnit Maven Plugin (https://github.com/Treeptik/cloudunit/blob/dev/documentation/README.md)

**Comment by zepouet** [comment]
Corrected
