### ISSUE TITLE
Shell scripts for auto installation

### ISSUE THREAD

**Issue by zepouet** [Treeptik/cloudunit#77]
* Rename ubuntu.sh to a correct version to be similar to the other one (16.04)
* Try to do functions to factorize the code. 
* Please reference the scripts into the documentation
* Never forget that a script can be played many times : need to detect the products already installed.
* After the installation, create an application into CloudUnit to valid the processus.
* Try to execute remote shell through **cur -sL .... | sudo bash** for example.

Please comment before to close the ticket.

Good job Guys ++

**Comment by GuillaumeUnice** [comment]
Rename ubuntu.sh to a correct version : DONE

Try to do functions to factorize the code : DONE

Please reference the scripts into the documentation : DONE

Never forget that a script can be played many times : need to detect the products already installed. : DONE

After the installation, create an application into CloudUnit to valid the processus. : DONE

Try to execute remote shell through cur -sL .... | sudo bash for example. : DONE (whithout sudo mode)
