### ISSUE TITLE
Setting JVM options failed.

### ISSUE THREAD

**Issue by mackristof** [Treeptik/CloudUnit#8]
when I setting JVM option on "JVM Configuration" tab on https://cu-tests.cloudunit.io/ and save changes, settings not displayed on field.

**Comment by zepouet** [comment]
Thanks for report.

Can you give ivm options you test please. At the moment, I test the platform with the three feature (jvm size, jvm options and ivm release) and it seems right.

We have a Integration Test to check all options so we could test your case.

Just for information if you set an invalid options, there is an automatic rollback to previous options.

Thanks a lot for your tests.
Best regards,

**Comment by mackristof** [comment]
-Dfile.encoding=UTF8 -Dgeotk.image.cache.size=128m -DDATABASE_URL=postgres://XXXXXX:XXXXXXX@johndoe-testcmo-postgresql-9-3-1.postgresql-9-3.cloud.unit:5432/testcmo -DEPSG_DATABASE_URL=postgres://XXXXXX:XXXXXX@johndoe-testcmo-postgresql-9-3-1.postgresql-9-3.cloud.unit:5432/testcmo

**Comment by zepouet** [comment]
It is an encoding problem. 

We need to encode URL for "/" with "\/"

So you can use :
```
-Dfile.encoding=UTF8 -Dgeotk.image.cache.size=128m -DDATABASE_URL=postgres:\/\/XXXXXX:XXXXXXX@johndoe-testcmo-postgresql-9-3-1.postgresql-9-3.cloud.unit:5432\/testcmo -DEPSG_DATABASE_URL=postgres:\/\/XXXXXX:XXXXXX@johndoe-testcmo-postgresql-9-3-1.postgresql-9-3.cloud.unit:5432\/testcmo
```

As result you will have in the runtime options for tomcat processus.
So we are sure the options are really used.

```
/cloudunit/java/jdk1.8.0_25/bin/java 
-Djava.util.logging.config.file=/cloudunit/appconf/conf/logging.properties
 -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Dfile.encoding=UTF-8 
-Xms1024m -Xmx1024m -XX:MaxPermSize=256m -Dfile.encoding=UTF8 
-Dgeotk.image.cache.size=128m 
-DDATABASE_URL=postgres://XXXXXX:XXXXXXX@johndoe-testcmo-postgresql-9-3-1.postgresql-9-3.cloud.unit:5432/testcmo
-DEPSG_DATABASE_URL=postgres://XXXXXX:XXXXXX@johndoe-testcmo-postgresql-9-3-1.postgresql-9-3.cloud.unit:5432/testcmo -Djava.endorsed.dirs=/cloudunit/binaries/endorsed 
-classpath /cloudunit/binaries/bin/bootstrap.jar:/cloudunit/binaries/bin/tomcat-juli.jar 
-Dcatalina.base=/cloudunit/appconf -Dcatalina.home=/cloudunit/binaries 
-Djava.io.tmpdir=/cloudunit/appconf/temp org.apache.catalina.startup.Bootstrap start
```

We will document this point and others too. Thanks for using the platform.

**Comment by mackristof** [comment]
thanks for quick help \o/
