### ISSUE TITLE
CRUD User between Gitlab and CU

### ISSUE THREAD

**Issue by zepouet** [Treeptik/cloudunit#80]
Create a GitlabService and others class to have a CRUD mechanism between CU and Gitlab.
An admin into CloudUnit can create, delete, update User into CloudUnit and others platforms like GitLab.

You need to think about
* Create methods  into GitlabService and GitlabServiceImpl
* Create GitLab API (fr.treeptik.cloudunit.dto.gitlab)
* Add security (Spring security hasRole for these methods)
* Call these methods if user is right created into CloudUnit

**Comment by Kan23** [comment]
Add and delete user on Gitlab methods are implemented. Update methods cannot be implemented because the function isn't possible in Cloudunit user page. Because the password criterion in Gitlab is different than Cloudunit, I change this criterion in UserServiceImpl file.
