### ISSUE TITLE
Upgrade Angular 1.3 to Angular 1.5

### ISSUE THREAD

**Issue by GuillaumeUnice** [Treeptik/cloudunit#98]
Analyze the state of the Art and prepare migration.

-Upgrade Angular 1.5.
-Upgrade module.
-Introduce Component.

**Comment by zepouet** [comment]
@GuillaumeUnice Can you give me a simple status about ? Merged ? Thanks ++

**Comment by GuillaumeUnice** [comment]
It's in the same branch of test e2e (here : [)](https://github.com/Treeptik/cloudunit/tree/98-newAngular1.5) currently : 
-Upgrade Angular 1.5 :  done
-Upgrade module : done
-Introduce Component : I just make a test in one directive, I think you can apply in all directives present in "components" directory

**Comment by GuillaumeUnice** [comment]
-Component : Done
